/* Generated by cbindgen — do not edit manually */

#ifndef SANCTUM_H
#define SANCTUM_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Result codes returned by FFI functions.
 *
 * 0 = success, negative values = errors.
 */
enum SanctumResult {
    /**
     * Operation succeeded.
     */
    OK = 0,
    /**
     * A null pointer was passed where a valid pointer was expected.
     */
    NULL_POINTER = -1,
    /**
     * A string argument was not valid UTF-8.
     */
    INVALID_UTF8 = -2,
    /**
     * The vault is not initialized at the given path.
     */
    NOT_INITIALIZED = -3,
    /**
     * Access was denied by policy.
     */
    ACCESS_DENIED = -4,
    /**
     * The requested credential was not found.
     */
    NOT_FOUND = -5,
    /**
     * A cryptographic or internal error occurred.
     */
    CRYPTO_ERROR = -6,
    /**
     * The provided output buffer is too small.
     */
    BUFFER_TOO_SMALL = -7,
    /**
     * JSON serialization/deserialization failed.
     */
    JSON_ERROR = -8,
    /**
     * A Rust panic was caught at the FFI boundary.
     */
    PANIC = -9,
    /**
     * An unknown or unclassified error.
     */
    UNKNOWN = -10,
};
typedef int32_t SanctumResult;

/**
 * Opaque vault handle exposed to C callers.
 */
typedef struct SanctumVault SanctumVault;

/**
 * Initialize a new vault at `path` with the given passphrase.
 *
 * Returns an opaque pointer to the vault, or null on failure.
 * The caller owns the pointer and must free it with `sanctum_vault_free`.
 */
struct SanctumVault *sanctum_vault_init(const char *path,
                                        const uint8_t *passphrase,
                                        uintptr_t passphrase_len);

/**
 * Open an existing vault at `path` and unlock it with the given passphrase.
 *
 * Returns an opaque pointer to the vault, or null on failure.
 * The caller owns the pointer and must free it with `sanctum_vault_free`.
 */
struct SanctumVault *sanctum_vault_open(const char *path,
                                        const uint8_t *passphrase,
                                        uintptr_t passphrase_len);

/**
 * Free a vault handle previously returned by `sanctum_vault_init` or `sanctum_vault_open`.
 *
 * Passing null is a no-op.
 */
void sanctum_vault_free(struct SanctumVault *vault);

/**
 * Store a credential in the vault.
 *
 * `policy_json` may be null for no policy. If non-null it must be a
 * NUL-terminated JSON string representing a `Policy` object.
 */
SanctumResult sanctum_vault_store(struct SanctumVault *vault,
                                  const char *name,
                                  const uint8_t *secret,
                                  uintptr_t secret_len,
                                  const char *agent_id,
                                  const char *policy_json);

/**
 * Retrieve a credential from the vault.
 *
 * On success, writes the secret bytes to `out_buf` (up to `*out_len` bytes)
 * and sets `*out_len` to the actual length. If the buffer is too small,
 * returns `SANCTUM_RESULT_BUFFER_TOO_SMALL` and sets `*out_len` to the
 * required size.
 */
SanctumResult sanctum_vault_retrieve(struct SanctumVault *vault,
                                     const char *name,
                                     const char *agent_id,
                                     uint8_t *out_buf,
                                     uintptr_t *out_len);

/**
 * Check whether policy allows an agent to retrieve a credential.
 *
 * Returns `SANCTUM_RESULT_OK` if allowed, `SANCTUM_RESULT_ACCESS_DENIED` if not.
 */
SanctumResult sanctum_vault_check_policy(struct SanctumVault *vault,
                                         const char *name,
                                         const char *agent_id);

/**
 * Query the audit log, optionally filtering by agent ID.
 *
 * Returns a JSON array of audit entries. On success, writes the JSON string
 * to `out_json` (up to `*out_len` bytes) and sets `*out_len` to the actual
 * length (excluding NUL terminator). If the buffer is too small, returns
 * `SANCTUM_RESULT_BUFFER_TOO_SMALL` with `*out_len` set to the required size.
 *
 * Pass null for `agent_id_filter` to get all entries.
 */
SanctumResult sanctum_vault_audit_log(struct SanctumVault *vault,
                                      const char *agent_id_filter,
                                      uint8_t *out_json,
                                      uintptr_t *out_len);

/**
 * Get the error message for the last failed operation on this thread.
 *
 * Returns a pointer to a NUL-terminated string valid until the next FFI call
 * on the same thread. Returns null if no error is recorded.
 */
const char *sanctum_error_message(void);

/**
 * Free a string previously returned by sanctum FFI functions.
 *
 * Passing null is a no-op.
 */
void sanctum_free_string(char *ptr);

#endif  /* SANCTUM_H */
